// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.19.1
// source: chat.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "chat";

export interface Conversation {
  id: string;
  participants: string[];
  /** direct | group */
  type: string;
  name: string;
  avatar: string;
  lastMessage: string;
  lastMessageAt: number;
  lastSenderId: string;
  unreadCounts: { [key: string]: number };
  admins: string[];
  isDeleted: boolean;
  createdAt: number;
  updatedAt: number;
}

export interface Conversation_UnreadCountsEntry {
  key: string;
  value: number;
}

export interface ConversationResponse {
  conversation: Conversation | undefined;
}

export interface Media {
  id: string;
  url: string;
  mimeType: string;
  type: string;
}

export interface User {
  id: string;
  username: string;
  fullName: string;
  avatar: string;
  verified: boolean;
}

export interface Message {
  id: string;
  conversationId: string;
  text: string;
  /** text | image | video | audio | file | gif */
  type: string;
  readBy: string[];
  reactions: { [key: string]: StringList };
  isDeleted: boolean;
  replyTo: string;
  createdAt: number;
  updatedAt: number;
  sender: User | undefined;
  media: Media[];
}

export interface Message_ReactionsEntry {
  key: string;
  value: StringList | undefined;
}

export interface StringList {
  values: string[];
}

export interface MessageResponse {
  message: Message | undefined;
}

export interface GetOrCreateConversationRequest {
  userId1: string;
  userId2: string;
}

export interface CreateGroupRequest {
  name: string;
  creatorId: string;
  participantIds: string[];
  avatar: string;
}

export interface AddGroupMemberRequest {
  conversationId: string;
  adminId: string;
  userId: string;
}

export interface SendMessageRequest {
  conversationId: string;
  senderId: string;
  senderName: string;
  senderAvatar: string;
  text: string;
  mediaIds: string[];
  type: string;
  replyTo: string;
}

export interface GetMessagesRequest {
  conversationId: string;
  userId: string;
  page: number;
  limit: number;
}

export interface DeleteMessageRequest {
  messageId: string;
  userId: string;
}

export interface MarkAsReadRequest {
  conversationId: string;
  userId: string;
}

export interface ReactToMessageRequest {
  messageId: string;
  userId: string;
  emoji: string;
}

export interface GetConversationsRequest {
  userId: string;
  page: number;
  limit: number;
}

export interface GetMessagesResponse {
  messages: Message[];
  total: number;
  page: number;
}

export interface ConversationItem {
  id: string;
  type: string;
  name: string;
  avatar: string;
  participants: string[];
  lastMessage: string;
  lastMessageAt: number;
  lastSenderId: string;
  unreadCount: number;
  isOnline: boolean;
}

export interface GetConversationsResponse {
  conversations: ConversationItem[];
  total: number;
  page: number;
}

export interface OperationResponse {
  success: boolean;
  message: string;
}

export const CHAT_PACKAGE_NAME = "chat";

export interface ChatServiceClient {
  /** Direct conversation */

  getOrCreateConversation(request: GetOrCreateConversationRequest): Observable<ConversationResponse>;

  /** Group */

  createGroup(request: CreateGroupRequest): Observable<ConversationResponse>;

  addGroupMember(request: AddGroupMemberRequest): Observable<OperationResponse>;

  /** Messages */

  sendMessage(request: SendMessageRequest): Observable<MessageResponse>;

  getMessages(request: GetMessagesRequest): Observable<GetMessagesResponse>;

  deleteMessage(request: DeleteMessageRequest): Observable<OperationResponse>;

  /** Read status */

  markAsRead(request: MarkAsReadRequest): Observable<OperationResponse>;

  /** Reactions */

  reactToMessage(request: ReactToMessageRequest): Observable<MessageResponse>;

  /** Conversation list */

  getConversations(request: GetConversationsRequest): Observable<GetConversationsResponse>;
}

export interface ChatServiceController {
  /** Direct conversation */

  getOrCreateConversation(
    request: GetOrCreateConversationRequest,
  ): Promise<ConversationResponse> | Observable<ConversationResponse> | ConversationResponse;

  /** Group */

  createGroup(
    request: CreateGroupRequest,
  ): Promise<ConversationResponse> | Observable<ConversationResponse> | ConversationResponse;

  addGroupMember(
    request: AddGroupMemberRequest,
  ): Promise<OperationResponse> | Observable<OperationResponse> | OperationResponse;

  /** Messages */

  sendMessage(request: SendMessageRequest): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  getMessages(
    request: GetMessagesRequest,
  ): Promise<GetMessagesResponse> | Observable<GetMessagesResponse> | GetMessagesResponse;

  deleteMessage(
    request: DeleteMessageRequest,
  ): Promise<OperationResponse> | Observable<OperationResponse> | OperationResponse;

  /** Read status */

  markAsRead(
    request: MarkAsReadRequest,
  ): Promise<OperationResponse> | Observable<OperationResponse> | OperationResponse;

  /** Reactions */

  reactToMessage(
    request: ReactToMessageRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  /** Conversation list */

  getConversations(
    request: GetConversationsRequest,
  ): Promise<GetConversationsResponse> | Observable<GetConversationsResponse> | GetConversationsResponse;
}

export function ChatServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getOrCreateConversation",
      "createGroup",
      "addGroupMember",
      "sendMessage",
      "getMessages",
      "deleteMessage",
      "markAsRead",
      "reactToMessage",
      "getConversations",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChatService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChatService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHAT_SERVICE_NAME = "ChatService";
