// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.19.1
// source: notification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "notification";

export interface GetNotificationsRequest {
  userId: string;
  page: number;
  limit: number;
}

export interface NotificationModel {
  id: string;
  toUserId: string;
  fromUserId: string;
  fromUserName: string;
  fromUserAvatar: string;
  type: string;
  title: string;
  body: string;
  isRead: boolean;
  createdAt: string;
  data: NotificationData | undefined;
}

export interface NotificationData {
  postId: string;
  commentId: string;
  groupId: string;
}

export interface GetNotificationsResponse {
  notifications: NotificationModel[];
  total: number;
  unreadCount: number;
  page: number;
}

export interface GetNotificationByIdRequest {
  userId: string;
  notificationId: string;
}

export interface MarkAsReadRequest {
  userId: string;
  notificationId: string;
}

export interface MarkAllAsReadRequest {
  userId: string;
}

export interface ActionResponse {
  success: boolean;
}

export const NOTIFICATION_PACKAGE_NAME = "notification";

export interface NotificationGrpcServiceClient {
  getNotifications(request: GetNotificationsRequest): Observable<GetNotificationsResponse>;

  getNotificationById(request: GetNotificationByIdRequest): Observable<NotificationModel>;

  markAsRead(request: MarkAsReadRequest): Observable<ActionResponse>;

  markAllAsRead(request: MarkAllAsReadRequest): Observable<ActionResponse>;
}

export interface NotificationGrpcServiceController {
  getNotifications(
    request: GetNotificationsRequest,
  ): Promise<GetNotificationsResponse> | Observable<GetNotificationsResponse> | GetNotificationsResponse;

  getNotificationById(
    request: GetNotificationByIdRequest,
  ): Promise<NotificationModel> | Observable<NotificationModel> | NotificationModel;

  markAsRead(request: MarkAsReadRequest): Promise<ActionResponse> | Observable<ActionResponse> | ActionResponse;

  markAllAsRead(request: MarkAllAsReadRequest): Promise<ActionResponse> | Observable<ActionResponse> | ActionResponse;
}

export function NotificationGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getNotifications", "getNotificationById", "markAsRead", "markAllAsRead"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("NotificationGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("NotificationGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_GRPC_SERVICE_NAME = "NotificationGrpcService";
