// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.19.1
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

/** ── Profile Messages ────────────────────────────── */
export interface GetProfileRequest {
  userId: string;
  requesterId: string;
}

export interface UpdateProfileRequest {
  userId: string;
  name?: string | undefined;
  bio?: string | undefined;
  avatarMediaId?: string | undefined;
  coverMediaId?: string | undefined;
  location?: string | undefined;
  website?: string | undefined;
  birthDate?: string | undefined;
}

export interface DeleteAccountRequest {
  userId: string;
}

export interface DeleteResponse {
  success: boolean;
  message: string;
}

/** ── Follow Messages ─────────────────────────────── */
export interface FollowRequest {
  followerId: string;
  targetId: string;
}

export interface FollowResponse {
  success: boolean;
  message: string;
  followersCount: number;
  isFollowing: boolean;
}

export interface IsFollowingResponse {
  isFollowing: boolean;
}

export interface PaginationRequest {
  userId: string;
  page: number;
  limit: number;
}

/** ── Search Messages ─────────────────────────────── */
export interface SearchRequest {
  query: string;
  requesterId: string;
  page: number;
  limit: number;
}

export interface SuggestionRequest {
  userId: string;
  limit: number;
}

/** ── Presence Messages ───────────────────────────── */
export interface PresenceRequest {
  userId: string;
}

export interface PresenceResponse {
  isOnline: boolean;
  lastSeen: number;
}

export interface UserMedia {
  id: string;
  url: string;
  mimeType: string;
  type: string;
}

export interface UserProfile {
  id: string;
  name: string;
  email: string;
  bio: string;
  avatar: UserMedia | undefined;
  coverImg: UserMedia | undefined;
  location: string;
  website: string;
  birthDate: string;
  followersCount: number;
  followingCount: number;
  postsCount: number;
  isFollowing: boolean;
  isOnline: boolean;
  createdAt: string;
}

export interface ProfileResponse {
  success: boolean;
  message: string;
  user: UserProfile | undefined;
}

export interface UsersListResponse {
  success: boolean;
  users: UserProfile[];
  total: number;
  page: number;
}

export interface GetUsersByIdsRequest {
  userIds: string[];
}

export interface GetFollowerIdsRequest {
  userId: string;
}

export interface FollowerIdsResponse {
  followerIds: string[];
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  /** Profile */

  getProfile(request: GetProfileRequest): Observable<ProfileResponse>;

  updateProfile(request: UpdateProfileRequest): Observable<ProfileResponse>;

  deleteAccount(request: DeleteAccountRequest): Observable<DeleteResponse>;

  /** Follow System */

  followUser(request: FollowRequest): Observable<FollowResponse>;

  unfollowUser(request: FollowRequest): Observable<FollowResponse>;

  getFollowers(request: PaginationRequest): Observable<UsersListResponse>;

  getFollowing(request: PaginationRequest): Observable<UsersListResponse>;

  isFollowing(request: FollowRequest): Observable<IsFollowingResponse>;

  /** Search & Suggest */

  searchUsers(request: SearchRequest): Observable<UsersListResponse>;

  getSuggestions(request: SuggestionRequest): Observable<UsersListResponse>;

  /** Presence */

  setOnline(request: PresenceRequest): Observable<PresenceResponse>;

  setOffline(request: PresenceRequest): Observable<PresenceResponse>;

  getOnlineStatus(request: PresenceRequest): Observable<PresenceResponse>;

  /** Internal — other services call */

  getUsersByIds(request: GetUsersByIdsRequest): Observable<UsersListResponse>;

  getFollowerIds(request: GetFollowerIdsRequest): Observable<FollowerIdsResponse>;
}

export interface UserServiceController {
  /** Profile */

  getProfile(request: GetProfileRequest): Promise<ProfileResponse> | Observable<ProfileResponse> | ProfileResponse;

  updateProfile(
    request: UpdateProfileRequest,
  ): Promise<ProfileResponse> | Observable<ProfileResponse> | ProfileResponse;

  deleteAccount(request: DeleteAccountRequest): Promise<DeleteResponse> | Observable<DeleteResponse> | DeleteResponse;

  /** Follow System */

  followUser(request: FollowRequest): Promise<FollowResponse> | Observable<FollowResponse> | FollowResponse;

  unfollowUser(request: FollowRequest): Promise<FollowResponse> | Observable<FollowResponse> | FollowResponse;

  getFollowers(
    request: PaginationRequest,
  ): Promise<UsersListResponse> | Observable<UsersListResponse> | UsersListResponse;

  getFollowing(
    request: PaginationRequest,
  ): Promise<UsersListResponse> | Observable<UsersListResponse> | UsersListResponse;

  isFollowing(
    request: FollowRequest,
  ): Promise<IsFollowingResponse> | Observable<IsFollowingResponse> | IsFollowingResponse;

  /** Search & Suggest */

  searchUsers(request: SearchRequest): Promise<UsersListResponse> | Observable<UsersListResponse> | UsersListResponse;

  getSuggestions(
    request: SuggestionRequest,
  ): Promise<UsersListResponse> | Observable<UsersListResponse> | UsersListResponse;

  /** Presence */

  setOnline(request: PresenceRequest): Promise<PresenceResponse> | Observable<PresenceResponse> | PresenceResponse;

  setOffline(request: PresenceRequest): Promise<PresenceResponse> | Observable<PresenceResponse> | PresenceResponse;

  getOnlineStatus(
    request: PresenceRequest,
  ): Promise<PresenceResponse> | Observable<PresenceResponse> | PresenceResponse;

  /** Internal — other services call */

  getUsersByIds(
    request: GetUsersByIdsRequest,
  ): Promise<UsersListResponse> | Observable<UsersListResponse> | UsersListResponse;

  getFollowerIds(
    request: GetFollowerIdsRequest,
  ): Promise<FollowerIdsResponse> | Observable<FollowerIdsResponse> | FollowerIdsResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getProfile",
      "updateProfile",
      "deleteAccount",
      "followUser",
      "unfollowUser",
      "getFollowers",
      "getFollowing",
      "isFollowing",
      "searchUsers",
      "getSuggestions",
      "setOnline",
      "setOffline",
      "getOnlineStatus",
      "getUsersByIds",
      "getFollowerIds",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
