services:
  chat-service:
    build:
      context: ../../
      dockerfile: apps/chat-service/Dockerfile
    image: ${DOCKER_USERNAME}/chat-service
    container_name: waave_chat_service
    env_file:
      - ../../.env
    ports:
      - '${CHAT_HTTP_PORT:-4005}:4005'
      - '${CHAT_GRPC_PORT:-3005}:3005'
    environment:
      - CHAT_MONGO_DB_URL=mongodb://mongo:mongo123@chat_mongo_db_1:27015,chat_mongo_db_2:27025,chat_mongo_db_3:27035/chat_db?replicaSet=chat-rs&authSource=admin
      - CHAT_REDIS_HOST=chat_redis
      - KAFKA_BROKERS=kafka:9092
      # gRPC peer services
      - AUTH_SERVICE_GRPC_URL=auth-service:3001
      - USER_SERVICE_GRPC_URL=user-service:3002
      - POST_SERVICE_GRPC_URL=post-service:3003
      - FEED_SERVICE_GRPC_URL=feed-service:3004
      - CHAT_SERVICE_GRPC_URL=chat-service:3005
      - E2EE_CHAT_SERVICE_GRPC_URL=e2ee-chat-service:3006
      - MEDIA_SERVICE_GRPC_URL=media-service:3009
      - NOTIFICATION_SERVICE_GRPC_URL=notification-service:3010
      - MCP_SERVICE_GRPC_URL=mcp-service:3011
    restart: unless-stopped
    networks:
      - waave

networks:
  waave:
    name: waave
    external: true
