services:
  notification-service:
    build:
      context: ../../
      dockerfile: apps/notification/Dockerfile
    image: ${DOCKER_USERNAME}/notification
    container_name: waave_notification_service
    env_file:
      - ../../.env
    ports:
      - '${NOTIFICATION_HTTP_PORT:-4010}:4010'
      - '${NOTIFICATION_GRPC_PORT:-3010}:3010'
    environment:
      - NOTIFICATION_MONGO_DB_URL=mongodb://mongo:mongo123@notification_mongo_db_1:27016,notification_mongo_db_2:27026,notification_mongo_db_3:27036/notification_db?replicaSet=notification-rs&authSource=admin
      - NOTIFICATION_REDIS_HOST=notification_redis
      - KAFKA_BROKERS=kafka:9092
      # gRPC peer services
      - AUTH_SERVICE_GRPC_URL=auth-service:3001
      - USER_SERVICE_GRPC_URL=user-service:3002
      - POST_SERVICE_GRPC_URL=post-service:3003
      - FEED_SERVICE_GRPC_URL=feed-service:3004
      - CHAT_SERVICE_GRPC_URL=chat-service:3005
      - E2EE_CHAT_SERVICE_GRPC_URL=e2ee-chat-service:3006
      - MEDIA_SERVICE_GRPC_URL=media-service:3009
      - NOTIFICATION_SERVICE_GRPC_URL=notification-service:3010
      - MCP_SERVICE_GRPC_URL=mcp-service:3011
    restart: unless-stopped
    networks:
      - waave

networks:
  waave:
    name: waave
    external: true
