name: Feed Service CI/CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/feed-service.yml"
      - ".github/workflows/_reusable-service-cicd.yml"
      - "apps/feed-service/**"
      - "libs/common/**"
      - "libs/kafka/**"
      - "libs/proto-schema/**"
      - "libs/grpc-clients/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig*.json"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/feed-service.yml"
      - "apps/feed-service/**"
      - "libs/common/**"
      - "libs/kafka/**"
      - "libs/proto-schema/**"
      - "libs/grpc-clients/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig*.json"
  workflow_dispatch: {}

# jobs:
#   ci-cd:
#     uses: ./.github/workflows/_reusable-service-cicd.yml
#     with:
#       service_name: feed-service
#       nest_project: feed-service
#       k8s_deployment: feed-service
#       ecr_repository: waave-feed-service

#     secrets:
#       AWS_GITHUB_ACTIONS_ROLE_ARN: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
#       AWS_REGION: ${{ vars.AWS_REGION }}
#       EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
